config:
  defaults:
    number:
      preprocessing:
        normalization: zscore
  trainer:
    learning_rate: 0.0065641986318142834
    max_bin: 74173
    max_depth: 369
    num_boost_round: 2811
    num_leaves: 162
    type: lightgbm_trainer
  model_type: gbm
